# LAB 2: Create an image with ADD instruction

# Create an image with ADD instruction
# Tag your image as labs-add:v1.0
# Create a container based on that image, and see the extracted tar file.

FROM alpine:latest

RUN apk update

ADD http://www.vlsitechnology.org/pharosc_8.4.tar.gz .