# LAB 1: Create an image with GIT installed

# Create an image with GIT installed
# Tag your image as labs-git:v1.0
# Create a container based on that image, and run git –version to check that it is installed correctly

FROM alpine:latest

RUN apk update && apk add git
