# LAB 5: Create an image with ENTRYPOINT instruction

# Create an image with ENTRYPOINT instruction(Exec Form)
# ENTRYPOINT instruction in Shell Form
# Override the existing ENTRYPOINT

FROM alpine:latest

ENTRYPOINT [ "/bin/echo", "I'm using the ENTRYPOINT exec instruction" ]
# ENTRYPOINT echo "I'm using the ENTRYPOINT shell instruction"